# Using multiple workflow .yaml files
# https://stackoverflow.com/questions/64009546/how-to-run-multiple-github-actions-workflows-from-sub-directories


# TODO
# Preventing concurrent workflows (e.g. multiple merges to master at once)
# https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
# From: https://github.community/t/how-to-limit-concurrent-workflow-runs/16844/


# If we decide to use Docker - Using local Dockerfile in pipeline:
#   steps:
#   - name: Check out code
#     uses: actions/checkout@v2
#   - name: Build docker images
#     run: docker build -t local < .devcontainer/Dockerfile # .devcontainer is the local path
#   - name: Run tests
#     run: docker run -it -v $PWD:/srv -w/srv local make test
#  OR
#   - name: Build docker images
#     run: docker-compose build
#   - name: Run tests
#     run: docker-compose run test
# Ref: https://stackoverflow.com/questions/61154750/use-local-dockerfile-in-a-github-action


name: CD


# Multiple ways to do this, including:
on:
  workflow_dispatch:
  # 1. Publish your release in GitHub and have your pipeline
  # react to deploy the package
  release:
    types: [published]

  # 2. Run the pipeline on merge to `master` and do the release/deploy then.
  # pull_request:
  #   types: [ closed ]
  #   branches: [ master ]

  # 3. Run on CI completion (the `if:` in the `deploy` job below would need updating accordingly)
  # workflow_run:
  #   branches: [ master ]
  #   workflows: [ 'CI' ]
  #   types: [ completed ]


defaults:
  run:
    shell: bash


jobs:
  cd-client-build:
    runs-on: ubuntu-latest
    needs: [ ci-build-and-upload-artifacts ]
    steps:
      - uses: actions/checkout@v2
      # TODO - Relative paths are finicky/often only work when using actions.
      # When making this file an official GitHub Workflow, update this block.
      - uses: ./.github/workflows/ci.yaml

  cd-deploy:
    runs-on: ubuntu-latest
    needs: [ cd-client-build ]
    # Only run on merge to master: https://github.community/t/depend-on-another-workflow/16311/3
    if: ${{ github.event.pull_request.merged || github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout repository branch
        uses: actions/checkout@v2

      - name: Client CD - Download CI output
        id: cd-download-artifacts
        needs: [ cd-client-build ]
        uses: actions/download-artifact@v3
        with:
          name: ci-build-and-upload-artifacts
          path: |
            dist

      - name: Deploy application
        needs: [ cd-download-artifacts ]
        run: |
          npm run deploy
