name: Client - Verify and Build
description: Installs, tests, and builds the front-end


# TODO Once GitHub supports paths in `uses` for reusable workflows instead of
# URLs, then convert this to a workflow.
#
# Make this workflow callable from other workflows.
# Allows special fields only accessible to workflows/jobs (e.g. `defaults`)
# to be used while still offering the portability/reusability of actions.
# See: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
#
# Can accept inputs and provide outputs - useful for e.g. using the build output
# for a deployment.
# See: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onworkflow_callinputs
# on: [ workflow_call ]


# Turns out you can't use `inputs` to define values in the YAML file itself.
# Neither `shell: ${{ inputs.shell }}`, `shell: $INPUT_SHELL`, nor `shell: INPUT_SHELL` work.
# So, just resort to duplicating code everywhere until GitHub gets their act together.
#
# inputs:
#   directory:
#     description: Directory in which to run the action
#     required: false
#     default: ./client
#   shell:
#     description: Shell in which to run step.run commands
#     required: false
#     default: bash


runs:
  # Allows the YAML file to be run from other workflows/actions. See: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-1
  using: composite

  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository branch
      uses: actions/checkout@v2

    - name: Set NodeJS version
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Client Install
      id: client-install
      shell: bash
      working-directory: ./
      run: |
        npm install

    - name: Client Verify
      id: client-verify
      shell: bash
      working-directory: ./
      run: |
        npm run verify
