name: Server - Verify and Build
description: Installs, tests, and builds the back-end


# This is for a sample Python back-end but it could easily be modified for any back-end system

runs:
  using: composite

  steps:
    - uses: actions/checkout@v2

    - name: Set NodeJS version
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Server Install
      id: server-install
      shell: bash
      working-directory: ./server
      run: |
        ./init-workspace

    - name: Server lint
      id: server-lint
      shell: bash
      working-directory: ./server
      # Run linter (server/lint.py) itself to avoid duplication of logic.
      # If it changes any files, exit with error (fail step) to show repo isn't formatted properly.
      # If the linter itself encounters an error, then fail as well.
      run: |
        ./lint --check

    - name: Server Tests
      id: server-test
      shell: bash
      working-directory: ./server
      run: |
        ./run_test
